import numpy as np
class XY:
    def __init__(self,t:float,L:int) -> None: ...
    def get_L(self) -> int: ...
    def get_t(self) -> float: ...
    def get_flush_length(self) -> int: ...
    def get_spin(self) -> 'np.ndarray': ...
    def get_e(self) -> 'np.ndarray': ...
    def get_m(self) -> 'np.ndarray': ...
    def get_h(self) -> 'np.ndarray': ...
    def set_spin(self, arr:'np.ndarray') -> None: ...
    def run(self, spacing:int) -> None: ...